<div class="ec-form">
<?php
$config = $this->getConfig();

if (!$config['key'] || !$config['secret'] || !$config['domain']):
    ?>
    <form action="<?= $this->getInstallActionUrl() ?>" method="post" enctype="multipart/form-data">
        <?php echo $this->getBlockHtml('formkey') ?>
        <p>
            <label for="key">Key</label>
            <input name="key" type="text" placeholder="Key" value="<?= $config['key'] ?>" required/>
        </p>
        <p>
            <label for="secret">Secret</label>
            <input name="secret" type="text" placeholder="Secret" value="<?= $config['secret'] ?>" required/>
        </p>
        <p>
            <label for="domain">Domain</label>
            <input name="domain" type="text" placeholder="Domain" value="<?= $config['domain'] ?>" required/>
        </p>

        <input type="submit" value="Save"/>
    </form>
<?php
else:
    $campaigns = $this->getCampaigns($config['key'], $config['secret'], $config['domain']);
    if (!$campaigns): echo '<p class="danger">Something went wrong, please make sure you have the correct api key, secret, and domain.</p>';
    else:
    ?>
    <form action="<?= $this->getActionUrl() ?>" method="post" enctype="multipart/form-data">
        <?php echo $this->getBlockHtml('formkey') ?>
        <div data-mage-init='{"accordion":{"openedState": "active", "collapsible": true, "active": false, "multipleCollapsible": false}}'>
            <div data-role="collapsible">
                <div class="col-title" data-role="trigger">
                    Api
                </div>
            </div>
            <div data-role="content">
                <p>
                    <label for="key">Key</label>
                    <input name="key" type="text" placeholder="Key" value="<?= $config['key'] ?>" required/>
                </p>
                <p>
                    <label for="secret">Secret</label>
                    <input name="secret" type="text" placeholder="Secret" value="<?= $config['secret'] ?>" required/>
                </p>
                <p>
                    <label for="domain">Domain</label>
                    <input name="domain" type="text" placeholder="Domain" value="<?= $config['domain'] ?>" required/>
                </p>
            </div>
            <div data-role="collapsible">
                <div class="col-title"  data-role="trigger">
                    Configuration
                </div>
            </div>
            <div data-role="content">
                <p>
                    <label for="price">Price</label>
                    <input name="price" type="number" placeholder="Price" value="<?= $config['price'] ?>" required/>
                </p>
                <p>
                    <label for="campaign">Campaign</label>
                    <select name="campaign" required>
                        <option value="">Select Campaign</option>
                        <?php foreach ($campaigns['data'] as $campaign): ?>
                            <option
                                value="<?= $campaign['id'] ?>"
                                <?php if ($config['campaign'] == $campaign['id']): echo 'selected'; endif ?>
                            >
                                <?= $campaign['name'] ?>
                            </option>
                        <?php endforeach; ?>
                    </select>
                </p>
            </div>
            <div  class="col-title" data-role="collapsible">
                <div data-role="trigger">
                    Template
                </div>
            </div>
            <div data-role="content">
                <p>
                    <label for="template">Add {{qr}} where you want to display the qr</label>
                    <textarea name="template" id="template"><?= $config['template'] ?></textarea>
                </p>
            </div>
        </div>
        <?php endif ?>
        <input type="submit" value="Save"/>
    </form>
<?php
endif
?>
</div>
<script>
    require([
        "jquery",
        "mage/translate",
        "mage/adminhtml/events",
        "mage/adminhtml/wysiwyg/tiny_mce/setup"
    ], function (jQuery) {
        wysiwygcompany_description = new wysiwygSetup("template", {
            "width": "99%",
            "height": "200px",
            "plugins": [{"name": "textcolor"}],
            "tinymce4": {
                "toolbar": "formatselect | forecolor backcolor bold italic underline | alignleft aligncenter alignright | bullist numlist | link charmap",
                "plugins": "advlist autolink lists link charmap media noneditable table contextmenu paste code help",
            }
        });
        wysiwygcompany_description.setup("exact");
    });
</script>
